name: Demo application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip

      - name: Deploy
        uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.SECRETE_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
          channelId: live